# TODO(xinnjie): distinct move cursor backward/left and move word forward/right, backward != left, some languages use backward as right
mappings:
  - id: "actions.cursor.wordRight"
    name: "Move to next word"
    description: "Move cursor to the end of the next word"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordRight"
      when: "editorTextFocus"
    zed:
      action: "editor::MoveToNextWordEnd"
      context: "Editor"
    intellij:
      action: "EditorNextWord"
    helix:
      command: "move_next_word_end"
      mode: "insert"
    xcode:
      textAction: "moveWordForward:"
  - id: "actions.cursor.wordPartRight"
    name: "Move to next subword"
    description: "Move cursor to the end of the next subword (hump)"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordPartRight"
      when: "textInputFocus"
    zed:
      action: "editor::MoveToNextSubwordEnd"
      context: "Editor"
    intellij:
      notSupported: true
      note: "intellij need to turn on `CamelHumps` setting"
    helix:
      command: "move_next_sub_word_start"
      mode: "insert"
    xcode:
      textAction: "moveSubWordForward:"
  - id: "actions.cursor.wordLeft"
    name: "Move to previous word"
    description: "Move cursor to the start of the previous word"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordLeft"
      when: "textInputFocus"
    zed:
      action: "editor::MoveToPreviousWordStart"
      context: "Editor"
    intellij:
      action: "EditorPreviousWord"
    helix:
      command: "move_prev_word_start"
      mode: "insert"
    xcode:
      textAction: "moveWordBackward:"
  - id: "actions.cursor.wordPartLeft"
    name: "Move to previous subword"
    description: "Move cursor to the start of the previous subword (hump)"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordPartStartLeft"
      when: "editorTextFocus"
    zed:
      action: "editor::MoveToPreviousSubwordStart"
      context: "Editor"
    intellij:
      notSupported: true
      note: "intellij need to turn on `CamelHumps` setting"
    helix:
      command: "move_prev_sub_word_start"
      mode: "insert"
    xcode:
      textAction: "moveSubWordBackward:"
  - id: "actions.cursor.wordRightSelect"
    name: "Select next word"
    description: "Select to the end of the next word"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordRightSelect"
      when: "editorTextFocus"
    zed:
      action: "editor::SelectToNextWordEnd"
      context: "Editor"
    intellij:
      action: "EditorNextWordWithSelection"
    helix:
      notSupported: true
      note: "helix move cursor with selection by default"
    xcode:
      textAction: "moveWordForwardAndModifySelection:"
  - id: "actions.cursor.wordPartRightSelect"
    name: "Select next subword"
    description: "Select to the end of the next subword (hump)"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordPartRightSelect"
      when: "textInputFocus"
    zed:
      action: "editor::SelectToNextSubwordEnd"
      context: "Editor"
    intellij:
      notSupported: true
      note: "intellij need to turn on `CamelHumps` setting"
    helix:
      notSupported: true
    xcode:
      textAction: "moveSubWordForwardAndModifySelection:"
  - id: "actions.cursor.wordLeftSelect"
    name: "Select previous word"
    description: "Select to the start of the previous word"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordLeftSelect"
      when: "textInputFocus"
    zed:
      action: "editor::SelectToPreviousWordStart"
      context: "Editor"
    intellij:
      action: "EditorPreviousWordWithSelection"
    helix:
      notSupported: true
      note: "helix move cursor with selection by default"
    xcode:
      textAction: "moveWordBackwardAndModifySelection:"
  - id: "actions.cursor.wordPartLeftSelect"
    name: "Select previous subword"
    description: "Select to the start of the previous subword (hump)"
    category: "Editor.Cursor.Word"
    vscode:
      command: "cursorWordPartStartLeftSelect"
      when: "editorTextFocus"
    zed:
      action: "editor::SelectToPreviousSubwordStart"
      context: "Editor"
    intellij:
      notSupported: true
      note: "intellij need to turn on `CamelHumps` setting"
    helix:
      notSupported: true
      note: "helix move cursor with selection by default"
    xcode:
      textAction: "moveSubWordBackwardAndModifySelection:"
