mappings:
  - id: "actions.cursor.lineStart"
    name: "Move to line start"
    description: "Move cursor to the beginning of the line"
    category: "Editor.Cursor.Line"
    vscode:
      command: "cursorLineStart"
      when: "textInputFocus"
    zed:
      action: "editor::MoveToBeginningOfLine"
      context: "Editor"
    intellij:
      action: "EditorLineStart"
    helix:
      command: "goto_line_start"
      mode: "insert"
    xcode:
      textAction: "moveToBeginningOfLine:"
  - id: "actions.cursor.lineEnd"
    name: "Move to line end"
    description: "Move cursor to the end of the line"
    category: "Editor.Cursor.Line"
    vscode:
      command: "cursorLineEnd"
      when: "textInputFocus"
    zed:
      action: "editor::MoveToEndOfLine"
      context: "Editor"
    intellij:
      action: "EditorLineEnd"
    helix:
      command: "goto_line_end"
      mode: "insert"
    xcode:
      textAction: "moveToEndOfLine:"
  - id: "actions.cursor.lineStartSelect"
    name: "Select line start"
    description: "Select from cursor to the beginning of the line"
    category: "Editor.Cursor.Line"
    vscode:
      command: "cursorLineStartSelect"
      when: "textInputFocus"
    zed:
      action: "editor::SelectToBeginningOfLine"
      context: "Editor"
    intellij:
      action: "EditorLineStartWithSelection"
    helix:
      command: "extend_to_line_start"
      mode: "insert"
  - id: "actions.cursor.lineEndSelect"
    name: "Select line end"
    description: "Select from cursor to the end of the line"
    category: "Editor.Cursor.Line"
    vscode:
      command: "cursorLineEndSelect"
      when: "textInputFocus"
    zed:
      action: "editor::SelectToEndOfLine"
      context: "Editor"
    intellij:
      action: "EditorLineEndWithSelection"
    helix:
      command: "extend_to_line_end"
      mode: "insert"
