mappings:
  - id: "actions.cursor.moveToTop"
    name: "Move to top"
    description: "Move caret to text start"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorTop"
      when: "textInputFocus"
    intellij:
      action: "EditorTextStart"
    zed:
      action: "editor::MoveToBeginning"
      context: "Editor"
    helix:
      command: "goto_file_start"
      mode: "insert"
    xcode:
      textAction: "scrollToBeginningOfDocument:"
  - id: "actions.cursor.moveToBottom"
    name: "Move to bottom"
    description: "Move caret to text end"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorBottom"
      when: "textInputFocus"
    intellij:
      action: "EditorTextEnd"
    zed:
      action: "editor::MoveToEnd"
      context: "Editor"
    helix:
      command: "goto_file_end"
      mode: "insert"
    xcode:
      textAction: "scrollToEndOfDocument:"
  - id: "actions.cursor.moveToTopSelect"
    name: "Select to top"
    description: "Select from cursor to text start"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorTopSelect"
      when: "textInputFocus"
    intellij:
      action: "EditorMoveToPageTopWithSelection"
    zed:
      action: "editor::SelectToBeginning"
      context: "Editor"
    helix:
      command: "extend_to_file_start"
      mode: "insert"
  - id: "actions.cursor.moveToBottomSelect"
    name: "Select to bottom"
    description: "Select from cursor to text end"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorBottomSelect"
      when: "textInputFocus"
    intellij:
      action: "EditorMoveToPageBottomWithSelection"
    zed:
      action: "editor::SelectToEnd"
      context: "Editor"
    helix:
      command: "extend_to_file_end"
      mode: "insert"
  - id: "actions.cursor.pageDown"
    name: "Page down"
    description: "Move cursor down by one page"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorPageDown"
      when: "textInputFocus"
    intellij:
      action: "EditorPageDown"
    zed:
      action: "editor::PageDown"
      context: "Editor"
    helix:
      command: "page_down"
      mode: "insert"
    xcode:
      textAction: "pageDown:"
  - id: "actions.cursor.pageDownSelect"
    name: "Select page down"
    description: "Select down by one page"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorPageDownSelect"
      when: "textInputFocus"
    intellij:
      action: "EditorPageDownWithSelection"
    zed:
      action: "editor::SelectPageDown"
      context: "Editor"
    helix:
      notSupported: true
  - id: "actions.cursor.pageUp"
    name: "Page up"
    description: "Move cursor up by one page"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorPageUp"
      when: "textInputFocus"
    intellij:
      action: "EditorPageUp"
    zed:
      action: "editor::PageUp"
      context: "Editor"
    helix:
      command: "page_up"
      mode: "insert"
    xcode:
      textAction: "pageUp:"
  - id: "actions.cursor.pageUpSelect"
    name: "Select page up"
    description: "Select up by one page"
    category: "Editor.Cursor.File"
    vscode:
      command: "cursorPageUpSelect"
      when: "textInputFocus"
    intellij:
      action: "EditorPageUpWithSelection"
    zed:
      action: "editor::SelectPageUp"
      context: "Editor"
    helix:
      notSupported: true
