mappings:
  - id: "actions.run.startDebugging"
    name: "Start debugging"
    description: "Start Debugging"
    category: "Debug"
    vscode:
      command: "workbench.action.debug.run"
      when: "debuggersAvailable && debugState == 'inactive'"
    zed:
      action: "debugger::Start"
    intellij:
      action: "Debug"
    helix:
      command: "dap_launch"
      mode: "insert"
    xcode:
      action: "runActiveRunContext:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.Run"
      commandID: "Xcode.IDEKit.CmdDefinition.Run"
      group: "Product Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Run"
  - id: "actions.run.stopDebugging"
    name: "Stop debugging"
    description: "Stop Debugging"
    category: "Debug"
    vscode:
      command: "workbench.action.debug.stop"
      when: "inDebugMode && !focusedSessionIsAttach"
    zed:
      action: "debugger::Stop"
    intellij:
      action: "Stop"
    helix:
      command: "dap_terminate"
      mode: "insert"
    xcode:
      notSupported: true
      note: "Use `Start debugging` instead"
  - id: "actions.run.restartDebugging"
    name: "Restart debugging"
    description: "Restart Debugging"
    category: "Debug"
    vscode:
      command: "workbench.action.debug.restart"
      when: "inDebugMode"
    zed:
      action: "debugger::RerunSession"
      context: ""
    intellij:
      action: "Rerun"
    helix:
      command: "dap_restart"
      mode: "insert"
    xcode:
      action: "cancelCurrentExecution:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.Stop"
      commandID: "Xcode.IDEKit.CmdDefinition.Stop"
      group: "Product Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Stop"
  - id: "actions.run.toggleBreakpoint"
    name: "Toggle breakpoint"
    description: "Toggle Breakpoint"
    category: "Debug"
    vscode:
      command: "editor.debug.action.toggleBreakpoint"
      when: "debuggersAvailable && disassemblyViewFocus || debuggersAvailable && editorTextFocus"
    zed:
      action: "editor::ToggleBreakpoint"
      context: "Editor"
    intellij:
      action: "ToggleLineBreakpoint"
    helix:
      command: "dap_toggle_breakpoint"
      mode: "insert"
    xcode:
      action: "toggleBreakpointAtCurrentLine:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.ToggleBreakpointAtCurrentLine"
      commandID: "Xcode.IDEKit.CmdDefinition.ToggleBreakpointAtCurrentLine"
      group: "Debug Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Breakpoints"
      title: "Create Breakpoint at Current Line"
  - id: "actions.view.showDebugOutputConsole"
    name: "Show debug console"
    description: "Show Debug Output Console view"
    category: "Debug"
    featured: true
    featuredReason: "Not all editors have debug console"
    vscode:
      command: "workbench.debug.action.toggleRepl"
      when: "workbench.panel.repl.view.active"
    zed:
      notSupported: true
      note: "zed do not have debug console"
    intellij:
      notSupported: true
      note: "intellij have debug output with DebugPanel"
    helix:
      notSupported: true
