mappings:
  - id: "actions.run.runTask"
    name: "Run task"
    description: "Run Task"
    category: "Run"
    vscode:
      command: "workbench.action.tasks.runTask"
      when: ""
    intellij:
      action: "ChooseRunConfiguration"
    zed:
      action: "task::Run"
      context: "Workspace"
  - id: "actions.run.reRunTask"
    name: "Re-run task"
    description: "Re-run last Task"
    category: "Run"
    vscode:
      command: "workbench.action.tasks.reRunTask"
      when: ""
    intellij:
      action: "Run"
    zed:
      action: "task::Rerun"
      context: "Workspace"
  - id: "actions.run.configureTaskRunner"
    name: "Configure tasks"
    description: "Configure Task Runner"
    category: "Run"
    vscode:
      command: "workbench.action.tasks.configureTaskRunner"
      when: ""
    intellij:
      action: "ShowProjectStructureSettings"
    zed:
      action: "zed::OpenTasks"
  - id: "actions.run.runBuildTask"
    name: "Run build task"
    description: "Run the default build task"
    category: "Run"
    vscode:
      command: "workbench.action.tasks.build"
      when: "taskCommandsRegistered"
    zed:
      notSupported: true
    intellij:
      action: "CompileDirty"
    xcode:
      action: "buildActiveRunContext:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.Build"
      group: "Product Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Build"
