mappings:
  - id: "actions.diff.compareTwoFiles"
    name: "Compare files"
    description: "Compare two files"
    category: "Tools.Diff"
    vscode:
      command: "compareSelected"
      when: "explorerViewletFocus"
    intellij:
      action: "CompareTwoFiles"
    zed:
      action: "project_panel::CompareMarkedFiles"
      context: "ProjectPanel"
  - id: "actions.diff.nextChange"
    name: "Next change"
    description: "Go to next change in compare editor"
    category: "Tools.Diff"
    vscode:
      command: "workbench.action.compareEditor.nextChange"
      when: "textCompareEditorVisible"
    intellij:
      action: "NextDiff"
    zed:
      action: "editor::GoToNextChange"
      context: "Editor && mode == full"
    xcode:
      - action: "jumpToNextChange:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextChange"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextChange"
        group: "Navigate Menu for Asset Catalog Comparison"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Jump to Next Change"
        disableImport: true
      - action: "jumpToNextChange:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextChange"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextChange"
        group: "Navigate Menu for Commit Sheet"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Jump to Next Change"
        disableImport: true
      - action: "jumpToNextChange:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextChange"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextChange"
        group: "Navigate Menu for Source Code"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Jump to Next Change"
  - id: "actions.diff.previousChange"
    name: "Previous change"
    description: "Go to previous change in compare editor"
    category: "Tools.Diff"
    vscode:
      command: "workbench.action.compareEditor.previousChange"
      when: "textCompareEditorVisible"
    intellij:
      action: "PreviousDiff"
    zed:
      action: "editor::GoToPreviousChange"
      context: "Editor && mode == full"
    xcode:
      - action: "jumpToPreviousChange:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToPreviousChange"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToPreviousChange"
        group: "Navigate Menu for Asset Catalog Comparison"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Jump to Previous Change"
        disableImport: true
      - action: "jumpToPreviousChange:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToPreviousChange"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToPreviousChange"
        group: "Navigate Menu for Commit Sheet"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Jump to Previous Change"
        disableImport: true
      - action: "jumpToPreviousChange:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToPreviousChange"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToPreviousChange"
        group: "Navigate Menu for Source Code"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Jump to Previous Change"
