mappings:
  - id: "actions.edit.deleteWordPartRight"
    name: "Delete next subword"
    description: "Delete to the end of the next subword (hump)"
    category: "Editor.Word"
    vscode:
      command: "deleteWordPartRight"
      when: "textInputFocus && !editorReadonly"
    zed:
      action: "editor::DeleteToNextSubwordEnd"
      context: "Editor"
    intellij:
      notSupported: true
      note: "behaviour is controlled by `CamelHumps` setting"
  - id: "actions.edit.deleteWordLeft"
    name: "Delete previous word"
    description: "Delete to the start of the previous word"
    category: "Editor.Word"
    vscode:
      command: "deleteWordLeft"
      when: "textInputFocus && !editorReadonly"
    zed:
      action: "editor::DeleteToPreviousWordStart"
      context: "Editor"
    intellij:
      action: "EditorDeleteToWordStart"
  - id: "actions.edit.deleteWordPartLeft"
    name: "Delete previous subword"
    description: "Delete to the start of the previous subword (hump)"
    category: "Editor.Word"
    vscode:
      command: "deleteWordPartLeft"
      when: "textInputFocus && !editorReadonly"
    zed:
      action: "editor::DeleteToPreviousSubwordStart"
      context: "Editor"
    intellij:
      notSupported: true
      note: "behaviour is controlled by `CamelHumps` setting"
  - id: "actions.edit.deleteWordRight"
    name: "Delete next word"
    description: "Delete to the end of the next word"
    category: "Editor.Word"
    vscode:
      command: "deleteWordRight"
      when: "textInputFocus && !editorReadonly"
    zed:
      action: "editor::DeleteToNextWordEnd"
      context: "Editor"
    intellij:
      action: "EditorDeleteToWordEnd"
