mappings:
  - id: "actions.view.toggleWordWrap"
    name: "Toggle word wrap"
    description: "Toggle word wrap in the editor"
    category: "Editor"
    featured: true
    vscode:
      command: "editor.action.toggleWordWrap"
    zed:
      action: "editor::ToggleSoftWrap"
      context: "Editor"
    intellij:
      notSupported: true
      note: "intellij has a `Soft-Wrap` configuration in settings"
    xcode:
      - action: "toggleWrapLines:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        group: "Editor Menu for Asset Catalog Comparison"
        groupID: "Xcode.DeltaComparisonEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Wrap Lines"
        disableImport: true
      - action: "toggleWrapLines:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        group: "GPU Debugger Menu for GPU Debugger"
        groupID: "GPUDebugger.Standard.EditorMenuDefinition"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Wrap Lines"
        disableImport: true
      - action: "toggleWrapLines:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        group: "GPU Debugger Menu for GPU Frame Debugger"
        groupID: "GPUDebugger.StandardAndAssistant.EditorMenuDefinition"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Wrap Lines"
        disableImport: true
      - action: "toggleWrapLines:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        group: "Editor Menu for Playground"
        groupID: "Xcode.IDEPlaygroundEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Wrap Lines"
        disableImport: true
      - action: "toggleWrapLines:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.WrapLines"
        group: "Editor Menu for Source Code"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Wrap Lines"
