mappings:
  - id: "actions.edit.formatDocument"
    name: "Format document"
    description: "Format Document"
    category: "Editor"
    vscode:
      - command: "editor.action.formatDocument"
        when: "editorHasDocumentFormattingProvider && editorTextFocus && !editorReadonly && !inCompositeEditor"
      - command: "notebook.format"
        when: "notebookEditable && !editorTextFocus && activeEditor == 'workbench.editor.notebook'"
        disableImport: true
    zed:
      action: "editor::Format"
      context: "Editor"
    intellij:
      action: "ShowReformatFileDialog"
  - id: "actions.edit.formatSelection"
    name: "Format selection"
    description: "Format Selection"
    category: "Editor"
    vscode:
      - command: "editor.action.formatSelection"
        when: "editorHasDocumentSelectionFormattingProvider && editorTextFocus && !editorReadonly"
      - command: "notebook.formatCell"
        when: "editorHasDocumentFormattingProvider && editorTextFocus && inCompositeEditor && notebookEditable && !editorReadonly && activeEditor == 'workbench.editor.notebook'"
        disableImport: true
    zed:
      action: "editor::FormatSelections"
      context: "Editor"
    intellij:
      action: "ReformatCode"
  - id: "actions.edit.reIndent"
    name: "Re-Indent code"
    description: "Re-Indent code"
    category: "Editor"
    featured: true
    featuredReason: "Use `FormatSelections` instead"
    xcode:
      action: "indentSelection:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ReIndent"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ReIndent"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Structure"
      title: "Re-Indent"
