mappings:
  - id: "actions.appearance.decreaseFontSize"
    name: "Decrease font size"
    description: "Decrease font size"
    category: "Editor.Appearance"
    xcode:
      action: "decreaseFontSize:"
      alternate: "NO"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.DecreaseFontSize"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Font Size"
      title: "Decrease"
  - id: "actions.appearance.increaseFontSize"
    name: "Increase font size"
    description: "Increase font size"
    category: "Editor.Appearance"
    xcode:
      action: "increaseFontSize:"
      alternate: "NO"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.IncreaseFontSize"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Font Size"
      title: "Increase"
