mappings:
  - id: "actions.refactor.rename"
    name: "Rename symbol"
    description: "Rename"
    category: "Code.Refactor"
    vscode:
      - command: "editor.action.rename"
        when: "editorHasRenameProvider && editorTextFocus && !editorReadonly"
      - command: "editor.action.changeAll"
        when: "!editorHasRenameProvider &&editorTextFocus && !editorReadonly"
        disableImport: true
      - command: "renameFile"
        disableImport: true
        when: "filesExplorerFocus && foldersViewVisible && !explorerResourceIsRoot && !explorerResourceReadonly && !inputFocus"
    intellij:
      action: "RenameElement"
    zed:
      action: "editor::Rename"
      context: "Editor"
    helix:
      command: "rename_symbol"
      mode: "insert"
    xcode:
      action: "renameRefactor:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Refactor.Rename"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Refactor.Rename"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Refactor"
      title: "Renameâ€¦"
  - id: "actions.refactor.refactor"
    name: "Refactor code"
    description: "Refactor This..."
    category: "Code.Refactor"
    vscode:
      command: "editor.action.refactor"
      when: "editorHasCodeActionsProvider && textInputFocus && !editorReadonly"
    intellij:
      action: "Refactorings.QuickListPopupAction"
    zed:
      notSupported: true
      note: "not supported yet, see [Code refactoring in Zed ](https://github.com/zed-industries/zed/discussions/8623)"
    helix:
      command: "code_action"
      mode: "insert"
  - id: "actions.refactor.organizeImports"
    name: "Organize imports"
    description: "Organize Imports"
    category: "Code.Refactor"
    vscode:
      command: "editor.action.organizeImports"
      when: "textInputFocus && !editorReadonly && supportedCodeAction =~ /(\\s|^)source\\.organizeImports\\b/"
    intellij:
      action: "OptimizeImports"
    zed:
      action: "editor::OrganizeImports"
      context: "Editor"
    helix:
      notSupported: true
  - id: "actions.refactor.quickFix"
    name: "Quick fix"
    description: "Quick Fix..."
    category: "Code.Refactor"
    vscode:
      command: "editor.action.quickFix"
      when: "editorHasCodeActionsProvider && textInputFocus && !editorReadonly"
    intellij:
      action: "ShowIntentionActions"
      disableImport: true
    zed:
      notSupported: true
      note: "not supported yet, no issue tracked"
    helix:
      notSupported: true
    xcode:
      - action: "fixAllIssues:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.FixAllInScope"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.FixAllInScope"
        group: "Editor Menu for Asset Catalog Comparison"
        groupID: "Xcode.DeltaComparisonEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Fix All Issues"
        disableImport: true
      - action: "fixAllIssues:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.FixAllInScope"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.FixAllInScope"
        group: "Editor Menu for Playground"
        groupID: "Xcode.IDEPlaygroundEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Fix All Issues"
        disableImport: true
      - action: "fixAllIssues:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.FixAllInScope"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.FixAllInScope"
        group: "Editor Menu for Source Code"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Fix All Issues"
  - id: "actions.refactor.codeAction"
    name: "Code action"
    description: "Code Action..."
    category: "Code.Refactor"
    vscode:
      command: "editor.action.codeAction"
      when: "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
    intellij:
      action: "ShowIntentionActions"
      disableImport: true
    zed:
      action: "editor::ToggleCodeActions"
      context: "Editor"
    helix:
      command: "code_action"
      mode: "insert"
    xcode:
      notSupported: true
  - id: "actions.refactor.sourceAction"
    name: "Generate codes"
    description: "Generate code... (Getters, Setters, Constructors, hashCode/equals, toString)"
    category: "Code.Refactor"
    vscode:
      command: "editor.action.sourceAction"
      when: "editorHasCodeActionsProvider && editorTextFocus && !editorReadonly"
    intellij:
      action: "Generate"
    zed:
      notSupported: true
      note: "Use `Code action` instead"
    xcode:
      noteSupported: true
  - id: "action.refactor.extractVariable"
    name: "Extract to variable"
    description: "Extract to variable"
    category: "Code.Refactor"
    featured: true
    xcode:
      action: "extractExpression:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Refactor.ExtractExpression"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Refactor.ExtractExpression"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Refactor"
      title: "Extract to Variable"
  - id: "action.refactor.extractMethod"
    name: "Extract to method"
    description: "Extract to method"
    category: "Code.Refactor"
    featured: true
    xcode:
      action: "extractMethod:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Refactor.ExtractMethod"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Refactor.ExtractMethod"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Refactor"
      title: "Extract to Method"
