mappings:
  - id: "actions.edit.find"
    name: "Find in file"
    description: "Find in current file"
    category: "Editor"
    vscode:
      command: "actions.find"
      when: "editorFocus || editorIsOpen"
    zed:
      action: "buffer_search::Deploy"
      context: "Editor"
    intellij:
      action: "Find"
    helix:
      command: "search"
      mode: "insert"
  - id: "actions.edit.nextMatchFindAction"
    name: "Find next"
    description: "Find Next"
    category: "Navigation"
    vscode:
      command: "editor.action.nextMatchFindAction"
      when: "editorFocus && findInputFocussed"
    intellij:
      action: "FindNext"
    zed:
      action: "search::SelectNextMatch"
      context: "Editor"
    helix:
      command: "search_next"
      mode: "insert"
    xcode:
      action: "selectNextOccurrence:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.SelectNextOccurrence"
      group: "Find Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Select Next Occurrence"
  - id: "actions.edit.previousMatchFindAction"
    name: "Find previous"
    description: "Find Previous"
    category: "Navigation"
    vscode:
      command: "editor.action.previousMatchFindAction"
      when: "editorFocus && findInputFocussed"
    intellij:
      action: "FindPrevious"
    zed:
      action: "search::SelectPreviousMatch"
      context: "Editor"
    helix:
      command: "search_prev"
      mode: "insert"
  - id: "actions.edit.replace"
    name: "Replace in file"
    description: "Replace in current file"
    category: "Editor"
    vscode:
      command: "editor.action.startFindReplaceAction"
      when: "editorFocus || editorIsOpen"
    zed:
      action: "buffer_search::DeployReplace"
      context: "Editor"
    intellij:
      action: "Replace"
    helix:
      notSupported: true
  - id: "actions.edit.findInFiles"
    name: "Find in project"
    description: "Find in all files in the project"
    category: "Editor"
    vscode:
      command: "workbench.action.findInFiles"
      when: "!explorerResourceIsFolder || !filesExplorerFocus"
    zed:
      action: "pane::DeploySearch"
      context: "Workspace"
    intellij:
      action: "FindInPath"
    helix:
      command: "global_search"
      mode: "insert"
    xcode:
      action: "findInWorkspace:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.FindInWorkspace"
      commandID: "Xcode.IDEKit.CmdDefinition.FindInWorkspace"
      group: "Find Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Find in Workspace…"
  - id: "actions.edit.replaceInFiles"
    name: "Replace in project"
    description: "Replace in all files in the project"
    category: "Editor"
    vscode:
      command: "workbench.action.replaceInFiles"
      when: ""
    zed:
      action: "pane::DeploySearch"
      args:
        "replace_enabled": true
      context: "Workspace"
    intellij:
      action: "ReplaceInPath"
    helix:
      notSupported: true
    xcode:
      action: "findAndReplaceInWorkspace:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.FindAndReplaceInWorkspace"
      group: "Find Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Find and Replace in Workspace…"
