mappings:
  - id: "actions.fold.fold"
    name: "Fold"
    description: "Collapse the current code block"
    category: "Editor.Folding"
    children:
      - "actions.fold.foldRecursively"
      - "actions.fold.foldAll"
    fallbacks:
      - "actions.fold.foldRecursively"
      - "actions.fold.foldAll"
    vscode:
      command: "editor.fold"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::Fold"
      context: "Editor"
    intellij:
      action: "CollapseRegion"
    xcode:
      action: "fold:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Fold"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Fold"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Code Folding"
      title: "Fold"
  - id: "actions.fold.unfold"
    name: "Unfold"
    description: "Expand the current code block"
    category: "Editor.Folding"
    children:
      - "actions.fold.unfoldRecursively"
      - "actions.fold.unfoldAll"
    fallbacks:
      - "actions.fold.unfoldRecursively"
      - "actions.fold.unfoldAll"
    vscode:
      command: "editor.unfold"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::UnfoldLines"
      context: "Editor"
    intellij:
      action: "ExpandRegion"
    xcode:
      action: "unfold:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Unfold"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.Unfold"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Code Folding"
      title: "Unfold"
  - id: "actions.fold.foldRecursively"
    name: "Fold recursively"
    description: "Collapse the current code block and its children recursively"
    category: "Editor.Folding"
    vscode:
      command: "editor.foldRecursively"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::FoldRecursive"
      context: "Editor"
    intellij:
      action: "CollapseRegionRecursively"
  - id: "actions.fold.unfoldRecursively"
    name: "Unfold recursively"
    description: "Expand the current code block and its children recursively"
    category: "Editor.Folding"
    vscode:
      command: "editor.unfoldRecursively"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::UnfoldRecursive"
      context: "Editor"
    intellij:
      action: "ExpandRegionRecursively"
  - id: "actions.fold.toggleFold"
    name: "Toggle fold"
    description: "Toggle Fold"
    category: "Editor.Folding"
    vscode:
      command: "editor.toggleFold"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::ToggleFold"
      context: "Editor"
    intellij:
      action: "ExpandCollapseToggleAction"
  - id: "actions.fold.foldAll"
    name: "Fold all"
    description: "Collapse all code blocks in the editor"
    category: "Editor.Folding"
    vscode:
      command: "editor.foldAll"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::FoldAll"
      context: "Editor"
    intellij:
      action: "CollapseAllRegions"
  - id: "actions.fold.unfoldAll"
    name: "Unfold all"
    description: "Expand all code blocks in the editor"
    category: "Editor.Folding"
    vscode:
      command: "editor.unfoldAll"
      when: "editorTextFocus && foldingEnabled"
    zed:
      action: "editor::UnfoldAll"
      context: "Editor"
    intellij:
      action: "ExpandAllRegions"
