mappings:
  - id: "actions.view.toggleWordWrap"
    name: "Toggle word wrap"
    description: "Toggle word wrap in the editor"
    category: "Editor"
    featured: true
    vscode:
      command: "editor.action.toggleWordWrap"
    zed:
      action: "editor::ToggleSoftWrap"
      context: "Editor"
    intellij:
      notSupported: true
      notSupportedReason: "intellij has a `Soft-Wrap` configuration in settings"
