mappings:
  - id: "actions.file.openFile"
    name: "Open file"
    description: "Open file dialog"
    category: "File"
    vscode:
      command: "workbench.action.files.openFile"
      when: "false"
    zed:
      action: "editor::OpenFile"
    intellij:
      action: "OpenFile"
    helix:
      command: "file_picker"
      mode: "insert"
    xcode:
      action: "openDocument:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.Open"
      commandID: "Xcode.IDEKit.CmdDefinition.Open"
      group: "File Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Openâ€¦"
  - id: "actions.file.showOpenedFileInNewWindow"
    name: "Show in new window"
    description: "Show opened file in new window"
    category: "File"
    vscode:
      command: "workbench.action.files.showOpenedFileInNewWindow"
      when: "emptyWorkspaceSupport"
    intellij:
      action: "EditSourceInNewWindow"
    zed:
      notSupported: true
      note: "Not support, no issue tracked"
    helix:
      notSupported: true
  - id: "actions.file.openRecent"
    name: "Open recent"
    description: "Open Recent"
    category: "File"
    vscode:
      - command: "workbench.action.openRecent"
        when: "!inQuickOpen"
      - command: "workbench.action.openPreviousEditorFromHistory"
        when: "inQuickOpen"
    intellij:
      action: "RecentFiles"
    zed:
      action: "projects::OpenRecent"
      context: "Workspace"
    helix:
      command: "buffer_picker"
      mode: "insert"
    xcode:
      action: "openInNewWindow:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.OpenInNewWindow"
      commandID: "Xcode.IDEKit.CmdDefinition.OpenInNewWindow"
      group: "File Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Open in New Window"
