mappings:
  - id: "actions.file.save"
    name: "Save file"
    description: "Save current file"
    category: "File"
    vscode:
      command: "workbench.action.files.save"
    zed:
      action: "workspace::Save"
      context: "Workspace"
    intellij:
      action: "SaveDocument"
    helix:
      command: ":write"
      mode: "insert"
    xcode:
      action: "ide_saveDocument:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.SaveDocument"
      commandID: "Xcode.IDEKit.CmdDefinition.SaveDocument"
      group: "File Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Save"
  - id: "actions.file.saveAll"
    name: "Save all"
    description: "Save all open files"
    category: "File"
    vscode:
      command: "workbench.action.files.saveAll"
    zed:
      action: "workspace::SaveAll"
      context: "Workspace"
    intellij:
      action: "SaveAll"
    helix:
      command: ":write-all"
      mode: "insert"
    xcode:
      notSupported: true
      note: "Xcode `Save all` is determined by `Save` keybinding"
  - id: "actions.file.saveAs"
    name: "Save as"
    description: "Save current file with a new name"
    category: "File"
    featured: true
    featuredReason: "Use `Save file` instead. Not all editors support `Save as`."
    vscode:
      command: "workbench.action.files.saveAs"
    zed:
      action: "workspace::SaveAs"
      context: "Workspace"
    intellij:
      notSupported: true
      note: "intellij do not have save as, you can use `Save file`."
    helix:
      notSupported: true
