mappings:
  - id: "actions.file.closeEditor"
    name: "Close file"
    description: "Close the active editor"
    category: "File"
    vscode:
      command: "workbench.action.closeActiveEditor"
      when: ""
    zed:
      action: "pane::CloseActiveItem"
      context: "Editor"
    intellij:
      action: "CloseContent"
    helix:
      command: ":buffer-close"
      mode: "insert"
    xcode:
      action: "dvt_closeActiveEditorTab:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.CloseEditorTab"
      commandID: "Xcode.IDEKit.CmdDefinition.CloseEditorTab"
      group: "File Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Close Tab, Editor Pane, Window Tab, or Window"
