mappings:
  - id: "actions.file.newFile"
    name: "New file"
    description: "Create a new file"
    category: "File"
    vscode:
      command: "workbench.action.files.newUntitledFile"
      when: ""
    zed:
      action: "workspace::NewFile"
      context: "Workspace"
    intellij:
      action: "NewScratchFile"
    xcode:
      action: "newFileFromTemplate:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.NewFileFromTemplate"
      commandID: "Xcode.IDEKit.CmdDefinition.NewFileFromTemplate"
      group: "File Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "New"
      title: "File from Templateâ€¦"
