mappings:
  - id: "actions.go.goToDeclaration"
    name: "Go to declaration"
    description: "Go to declaration or usages"
    category: "Code.Go"
    vscode:
      command: "editor.action.goToDeclaration"
      when: "editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !peekViewVisible"
    intellij:
      action: "GotoDeclaration"
    zed:
      action: "editor::GoToDeclaration"
      context: "Editor"
  - id: "actions.go.peekDeclaration"
    name: "Peek declaration"
    description: "Peek declaration"
    category: "Code.Go"
    vscode:
      command: "editor.action.previewDeclaration"
      when: "editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !peekViewVisible"
    intellij:
      action: "QuickImplementations"
      disableImport: true
    zed:
      action: "editor::GoToDefinitionSplit"
      context: "Editor"
  - id: "actions.go.implementations"
    name: "Go to implementations"
    description: "Go to implementations, For an interface, this shows all the implementors of that interface and for abstract methods, this shows all concrete implementations of that method."
    category: "Code.Go"
    vscode:
      command: "editor.action.goToImplementation"
      when: "editorHasImplementationProvider && editorTextFocus"
    zed:
      action: "editor::GoToImplementation"
      context: "Editor"
    intellij:
      action: "GotoImplementation"
  - id: "actions.go.goToTest"
    name: "Go to test"
    description: "Go to test"
    category: "Code.Go"
    vscode:
      command: "java.test.goToTest"
      when: "editorTextFocus && java:testRunnerActivated"
    intellij:
      action: "GotoTest"
    zed:
      notSupported: true
      notSupportedReason: "not supported yet, see [`Go to test` discussion](https://github.com/zed-industries/zed/discussions/40859)"
  - id: "actions.go.goToSuper"
    name: "Go to super"
    description: "Go to super class/super method"
    category: "Code.Go"
    vscode:
      command: "dart.goToSuper"
      when: "editorTextFocus && dart.isTestFile != true && dart.isTestFile != true"
    zed:
      notSupported: true
      notSupportedReason: "not supported yet, no issue tracked"
    intellij:
      action: "GotoSuperMethod"
  - id: "actions.go.definition"
    name: "Go to definition"
    description: "Go to definition"
    category: "Code.Go"
    vscode:
      command: "editor.action.revealDefinition"
      when: "editorHasDefinitionProvider && editorTextFocus"
    zed:
      action: "editor::GoToDefinition"
      context: "Editor"
    intellij:
      notSupported: true
      notSupportedReason: "There is not `Go to definition` in intellij, use `Go to declaration` instead"
    xcode:
      action: "editorContext_jumpToDefinition:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.JumpToDefinition"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Jump to Definition"
  - id: "actions.go.definitionPeek"
    name: "Peek definition"
    description: "Peek definition"
    category: "Code.Go"
    vscode:
      command: "editor.action.peekDefinition"
      when: "ditorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor"
    zed:
      notSupported: true
      notSupportedReason: "Peek is not supported yet, see [`Peek or Preview Definitions Inline` discussion](https://github.com/zed-industries/zed/discussions/28282)"
    intellij:
      action: "QuickImplementations"
  - id: "actions.go.typeDefinition"
    name: "Go to type definition"
    description: "Go to type definition"
    category: "Code.Go"
    vscode:
      command: "editor.action.goToTypeDefinition"
      when: "editorTextFocus"
    zed:
      action: "editor::GoToTypeDefinition"
      context: "Editor"
    intellij:
      action: "GotoTypeDeclaration"
  - id: "actions.go.typeDefinitionPeek"
    name: "Peek type definition"
    description: "Peek type definition"
    category: "Code.Go"
    vscode:
      command: "editor.action.peekTypeDefinition"
      when: "editorTextFocus"
    zed:
      notSupported: true
      notSupportedReason: "Peek is not supported yet, see [`Peek or Preview Definitions Inline` discussion](https://github.com/zed-industries/zed/discussions/28282)"
    intellij:
      action: "QuickTypeDefinition"
  - id: "actions.go.references"
    name: "Go to references"
    description: "Go to references"
    category: "Code.Go"
    vscode:
      command: "references-view.findReferences"
      when: "editorHasReferenceProvider"
    zed:
      action: "editor::FindAllReferences"
      context: "Editor"
    intellij:
      action: "FindUsages"
    xcode:
      action: "findSelectedSymbolInWorkspace:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.FindSelectedSymbolInWorkspace"
      group: "Find Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Find Selected Symbol in Workspace"
  - id: "actions.go.referencePeek"
    name: "Reference peek"
    description: "Show usages / reference search"
    category: "Code.Go"
    vscode:
      command: "editor.action.referenceSearch.trigger"
      when: "editorHasReferenceProvider && editorTextFocus && !inReferenceSearchEditor"
    intellij:
      action: "ShowUsages"
    zed:
      notSupported: true
      notSupportedReason: "Peek is not supported yet, see [`Peek or Preview Definitions Inline` discussion](https://github.com/zed-industries/zed/discussions/28282)"
  - id: "actions.go.callHierarchy"
    name: "Call hierarchy"
    description: "Show call hierarchy"
    category: "Code.Go"
    vscode:
      command: "references-view.showCallHierarchy"
      when: "editorHasCallHierarchyProvider && editorTextFocus"
    intellij:
      action: "CallHierarchy"
    zed:
      notSupported: true
      notSupportedReason: "not supported yet, see [`Support 'Show Call Hierarchy' as an LSP action` issue](https://github.com/zed-industries/zed/issues/14203)"
    xcode:
      action: "callHierarchy:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.CallHierarchy"
      group: "Find Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Find Call Hierarchy"
  - id: "actions.go.callHierarchyPeek"
    name: "Peek call hierarchy"
    description: "Peek call hierarchy"
    category: "Code.Go"
    featured: true
    featuredReason: "Use `CallHierarchy` instead"
    vscode:
      command: "editor.showCallHierarchy"
      when: "editorHasCallHierarchyProvider && editorTextFocus && !inReferenceSearchEditor"
    zed:
      notSupported: true
      notSupportedReason: "not supported yet, see [`Support 'Show Call Hierarchy' as an LSP action` issue](https://github.com/zed-industries/zed/issues/14203)"
    intellij:
      notSupported: true
      notSupportedReason: "Use `CallHierarchy` instead"
  - id: "actions.go.typeHierarchy"
    name: "Type hierarchy"
    description: "Show type hierarchy"
    category: "Code.Go"
    vscode:
      command: "java.action.showTypeHierarchy"
      when: "editorLangId == java && javaLSReady && editorTextFocus"
    intellij:
      action: "TypeHierarchy"
    zed:
      notSupported: true
      notSupportedReason: "Not supported yet, see [`Type hierarchy (class inheritance tree) support` discussion](https://github.com/zed-industries/zed/discussions/16348)"
  - id: "actions.go.bracket"
    name: "Go to bracket"
    description: "Go to bracket"
    category: "Code.Go"
    vscode:
      command: "editor.action.jumpToBracket"
      when: "editorTextFocus"
    zed:
      action: "editor::MoveToEnclosingBracket"
      context: "Editor"
    intellij:
      action: "EditorMatchBrace"
  - id: "actions.go.jumpToNextCounterpart"
    name: "Jump to next counterpart"
    description: "Jump to next counterpart, like switching between .cpp file and .h file"
    category: "Code.Go"
    featured: true
    xcode:
      action: "jumpToNextCounterpart:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextCounterpart"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.JumpToNextCounterpart"
      group: "Navigate Menu for Asset Catalog Comparison"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Navigate"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Jump to Next Counterpart"
