mappings:
  - id: "actions.go.back"
    name: "Go back"
    description: "Go to previous cursor location"
    category: "Navigation.History"
    vscode:
      command: "workbench.action.navigateBack"
      when: "canNavigateBack"
    zed:
      action: "pane::GoBack"
    intellij:
      action: "Back"
    xcode:
      action: "goBackInHistoryByCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.GoBack"
      commandID: "Xcode.IDEKit.CmdDefinition.GoBack"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Show Previous Location in History"
  - id: "actions.go.forward"
    name: "Go forward"
    description: "Go to next cursor location"
    category: "Navigation.History"
    vscode:
      command: "workbench.action.navigateForward"
      when: "canNavigateForward"
    zed:
      action: "pane::GoForward"
    intellij:
      action: "Forward"
    xcode:
      action: "goForwardInHistoryByCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.GoForward"
      commandID: "Xcode.IDEKit.CmdDefinition.GoForward"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Show Next Location in History"
  - id: "actions.go.lastEditLocation"
    name: "Go to last edit location"
    description: "Go to last edit location"
    category: "Navigation.History"
    vscode:
      command: "workbench.action.navigateToLastEditLocation"
    zed:
      notSupported: true
      note: "not supported yet, see [Implement \"Go To Last Edit Location\" issue](https://github.com/zed-industries/zed/issues/19731)"
    intellij:
      action: "JumpToLastChange"
