mappings:
  - id: "actions.go.line"
    name: "Go to line"
    description: "Go to Line/Column"
    category: "Navigation"
    vscode:
      command: "workbench.action.gotoLine"
      when: ""
    zed:
      action: "go_to_line::Toggle"
      context: "Editor"
    intellij:
      action: "GotoLine"
    xcode:
      notSupported: true
      note: "Use `Cmd+L` to go to line, this keybinding is not configurable"
