mappings:
  - id: "actions.go.nextProblem"
    name: "Next problem"
    description: "Go to Next Problem (Error, Warning, Info)"
    category: "Navigation.Problems"
    vscode:
      command: "editor.action.marker.next"
      when: "editorFocus"
    zed:
      action: "editor::GoToDiagnostic"
      args: {"severity": {"min": "hint", "max": "error"}}
      context: "Editor"
    intellij:
      action: "GotoNextError"
    xcode:
      action: "jumpToNextIssue:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.JumpToNextIssue"
      commandID: "Xcode.IDEKit.CmdDefinition.JumpToNextIssue"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Jump to Next Issue"
  - id: "actions.go.previousProblem"
    name: "Previous problem"
    description: "Go to Previous Problem (Error, Warning, Info)"
    category: "Navigation.Problems"
    vscode:
      command: "editor.action.marker.prev"
      when: "editorFocus"
    zed:
      action: "editor::GoToPreviousDiagnostic"
      args: {"severity": {"min": "hint", "max": "error"}}
      context: "Editor"
    intellij:
      action: "GotoPreviousError"
    xcode:
      action: "jumpToPreviousIssue:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.JumpToPreviousIssue"
      commandID: "Xcode.IDEKit.CmdDefinition.JumpToPreviousIssue"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Jump to Previous Issue"
