mappings:
  - id: "actions.edit.undo"
    name: "Undo action"
    description: "Undo last action"
    category: "Redo & Undo"
    vscode:
      command: "undo"
    zed:
      action: "editor::Undo"
      context: "Editor"
    intellij:
      action: "$Undo"
    helix:
      command: "undo"
      mode: "insert"
    xcode:
      textAction: "undo:"
  - id: "actions.edit.redo"
    name: "Redo action"
    description: "Redo last undone action"
    category: "Redo & Undo"
    vscode:
      command: "redo"
    zed:
      action: "editor::Redo"
      context: "Editor"
    intellij:
      action: "$Redo"
    helix:
      command: "redo"
      mode: "insert"
    xcode:
      textAction: "redo:"
