mappings:
  - id: "actions.run.stepOver"
    name: "Step over"
    description: "Step Over"
    category: "Debug.Step"
    vscode:
      command: "workbench.action.debug.stepOver"
      when: "debugState == 'stopped'"
    zed:
      action: "debugger::StepOver"
      context: "Workspace"
    intellij:
      action: "StepOver"
    helix:
      command: "dap_next"
      mode: "insert"
  - id: "actions.run.stepInto"
    name: "Step into"
    description: "Step Into"
    category: "Debug.Step"
    vscode:
      command: "workbench.action.debug.stepInto"
      when: "debugState != 'inactive'"
    zed:
      action: "debugger::StepInto"
      context: "Workspace"
    intellij:
      action: "StepInto"
    helix:
      command: "dap_step_in"
      mode: "insert"
  - id: "actions.run.stepOut"
    name: "Step out"
    description: "Step Out"
    category: "Debug.Step"
    vscode:
      command: "workbench.action.debug.stepOut"
      when: "debugState == 'stopped'"
    zed:
      action: "debugger::StepOut"
      context: "Workspace"
    intellij:
      action: "StepOut"
    helix:
      command: "dap_step_out"
      mode: "insert"
  - id: "actions.run.continue"
    name: "Continue"
    description: "Continue"
    category: "Debug.Step"
    vscode:
      command: "workbench.action.debug.continue"
      when: "debugState == 'stopped'"
    zed:
      action: "debugger::Continue"
      context: "Workspace"
    intellij:
      action: "Resume"
    helix:
      command: "dap_continue"
      mode: "insert"
  - id: "actions.run.runToCursor"
    name: "Run to cursor"
    description: "Run to Cursor"
    category: "Debug.Step"
    vscode:
      command: "editor.debug.action.runToCursor"
      when: "inDebugMode && debugState == 'stopped'"
    intellij:
      action: "RunToCursor"
    zed:
      action: "debugger::RunToCursor"
      context: "Workspace"
    helix:
      notSupported: true
    xcode:
      action: "continueToCurrentLine:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.ContinueToCurrentLine"
      commandID: "Xcode.IDEKit.CmdDefinition.ContinueToCurrentLine"
      group: "Debug Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Continue To Current Line"
