mappings:
  - id: "actions.selection.toggleColumnSelectionMode"
    name: "Toggle column selection"
    description: "Toggle column selection."
    category: "Editor.Selection"
    # vscode could also presee `option` to cloumn select
    vscode:
      command: "editor.action.toggleColumnSelection"
      when: "editorTextFocus"
    zed:
      notSupported: true
      note: "holding shift-option and perform a cursor drag to column select, see detail in [Add support for column selection mode issue](https://github.com/zed-industries/zed/issues/7215)"
    intellij:
      action: "EditorToggleColumnMode"
    helix:
      notSupported: true
