mappings:
  - id: "actions.selection.copyLineUp"
    name: "Copy line up"
    description: "Copy current line up"
    category: "Editor.Line"
    vscode:
      command: "editor.action.copyLinesUpAction"
      when: "editorTextFocus && !editorReadonly"
    zed:
      action: "editor::DuplicateLineUp"
      context: "Editor"
    intellij:
      notSupported: true
      notSupportedReason: "not supported, no ticket tracked"
    helix:
      command: "copy_selection_on_prev_line"
      mode: "insert"
  - id: "actions.selection.copyLineDown"
    name: "Copy line down"
    description: "Copy current line down"
    category: "Editor.Line"
    vscode:
      command: "editor.action.copyLinesDownAction"
      when: "editorTextFocus && !editorReadonly"
    zed:
      action: "editor::DuplicateLineDown"
      context: "Editor"
    intellij:
      action: "EditorDuplicate"
    helix:
      command: "copy_selection_on_next_line"
      mode: "insert"
    xcode:
      action: "duplicate:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.Duplicate"
      group: "Edit Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Duplicate"
  - id: "actions.selection.moveLineUp"
    name: "Move line up"
    description: "Move current line up"
    category: "Editor.Line"
    vscode:
      command: "editor.action.moveLinesUpAction"
      when: "editorTextFocus && !editorReadonly"
    zed:
      action: "editor::MoveLineUp"
      context: "Editor"
    intellij:
      action: "MoveLineUp"
    helix:
      command: "move_line_up"
      mode: "insert"
    xcode:
      action: "moveCurrentLineUp:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.MoveLineUp"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.MoveLineUp"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Structure"
      title: "Move Line Up"
  - id: "actions.selection.moveLineDown"
    name: "Move line down"
    description: "Move current line down"
    category: "Editor.Line"
    vscode:
      command: "editor.action.moveLinesDownAction"
      when: "editorTextFocus && !editorReadonly"
    zed:
      action: "editor::MoveLineDown"
      context: "Editor"
    intellij:
      action: "MoveLineDown"
    helix:
      notSupported: true
    xcode:
      action: "moveCurrentLineDown:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.MoveLineDown"
      commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.MoveLineDown"
      group: "Editor Menu for Source Code"
      groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Structure"
      title: "Move Line Down"
