mappings:
  - id: "actions.tabSwitcher.next"
    name: "Next tab"
    description: "Switch to next tab"
    category: "View Management.Tab"
    vscode:
      - command: "workbench.action.quickOpenPreviousRecentlyUsedEditorInGroup"
        when: "editorFocus"
      - command: "workbench.action.quickOpenNavigateNextInEditorPicker"
        when: "inEditorsPicker && inQuickOpen"
        disableImport: true
      - command: "workbench.action.quickOpenNavigateNext"
        disableImport: true
        when: "inQuickOpen"
      - command: "workbench.action.terminal.focusNext"
        when: "terminalFocus"
    zed:
      action: "tab_switcher::Toggle"
      context: "Workspace"
    intellij:
      action: "NextTab"
    xcode:
      action: "_showNextEditorTab:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.ShowNextEditorTab"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Show Next Tab"
  - id: "actions.tabSwitcher.previous"
    name: "Previous tab"
    description: "Switch to previous tab"
    category: "View Management.Tab"
    vscode:
      - command: "workbench.action.quickOpenLeastRecentlyUsedEditorInGroup"
        when: "editorFocus"
      - command: "workbench.action.quickOpenNavigatePreviousInEditorPicker"
        when: "inEditorsPicker && inQuickOpen"
        disableImport: true
      - command: "workbench.action.terminal.focusPrevious"
        disableImport: true
        when: "terminalFocus"
    zed:
      action: "tab_switcher::Toggle"
      context: "Workspace"
      args:
        select_last: true
    intellij:
      action: "PreviousTab"
    xcode:
      action: "_showPreviousEditorTab:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.ShowPreviousEditorTab"
      group: "Navigate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "YES"
      title: "Show Previous Tab"
