mappings:
  # TODO(xinnjie): Unify new operation. When in terminal view, create a new terminal; When in editor view, create a new file
  - id: "actions.terminal.new"
    name: "New terminal"
    description: "Create a new terminal"
    category: "Terminal"
    vscode:
      command: "workbench.action.terminal.new"
      when: "terminalProcessSupported || terminalWebExtensionContributedProfile"
    zed:
      action: "workspace::NewTerminal"
      context: "Workspace"
    intellij:
      action: "Terminal.NewTab"
    xcode:
      notSupported: true
      note: "Xcode does not have a terminal"
