mappings:
  - id: "actions.git.commitAll"
    name: "Commit all"
    description: "Commit All"
    category: "Version Control"
    vscode:
      command: "git.commitAll"
      when: "git.state == 'initialized' && git.hasChangesToCommit"
    intellij:
      action: "CheckinProject"
    zed:
      action: "git::Commit"
      context: "Editor"
    xcode:
      action: "commitCommand:"
      alternate: "NO"
      commandID: "Xcode.IDEKit.CmdDefinition.CommitCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Commit…"
  - id: "actions.git.openChanges"
    name: "Open changes"
    description: "Open all git changed files"
    category: "Version Control"
    vscode:
      command: "git.openChange"
      when: "git.state == 'initialized' && scmProvider == 'git' && resourceScheme == 'file'"
    intellij:
      action: "Diff.ShowDiff"
    zed:
      action: "git::OpenModifiedFiles"
      context: "Editor"
    xcode:
      action: "openInEditorTabs:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.OpenInEditorTabs"
      commandID: "Xcode.IDEKit.CmdDefinition.OpenInEditorTabs"
      group: "File Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Open in New Tabs"
  - id: "actions.git.unstage"
    name: "Unstage changes"
    description: "Unstage Changes"
    category: "Version Control"
    vscode:
      command: "git.unstageSelectedRanges"
      when: "editorTextFocus && isInDiffEditor && isInDiffRightEditor && !operationInProgress && resourceScheme == 'git'"
    intellij:
      action: "ChangesView.Revert"
    zed:
      action: "git::UnstageAndNext"
      context: "Editor && !agent_diff"
    xcode:
      action: "unstageWorkingCopiesCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.UnstageWorkingCopiesCommand"
      commandID: "Xcode.IDEKit.CmdDefinition.UnstageWorkingCopiesCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Unstage All Changes"
  - id: "actions.git.unstageSelected"
    name: "Unstage selected changes"
    description: "Unstage selected changes"
    category: "Version Control"
    xcode:
      action: "unstageSelectedFilesCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.UnstageSelectedFilesCommand"
      commandID: "Xcode.IDEKit.CmdDefinition.UnstageSelectedFilesCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Unstage Selected Files"
  - id: "actions.git.revert"
    name: "Revert changes"
    description: "Revert Changes"
    category: "Version Control"
    vscode:
      command: "git.revertSelectedRanges"
      when: "editorTextFocus && !operationInProgress && resourceScheme == 'file'"
    intellij:
      action: "Vcs.RollbackChangedLines"
    zed:
      action: "git::Restore"
      context: "Editor"
  - id: "actions.git.stage"
    name: "Stage changes"
    description: "Stage Changes"
    category: "Version Control"
    vscode:
      command: "git.stageSelectedRanges"
      when: "editorTextFocus && !operationInProgress && resourceScheme == 'file'"
    intellij:
      action: "ChangesView.Add"
    zed:
      action: "git::StageAndNext"
      context: "Editor && !agent_diff"
    xcode:
      action: "stageWorkingCopiesCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.StageWorkingCopiesCommand"
      commandID: "Xcode.IDEKit.CmdDefinition.StageWorkingCopiesCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Stage All Changes"
  - id: "actions.git.stageSelected"
    name: "Stage selected changes"
    description: "Stage Selected Changes"
    category: "Version Control"
    xcode:
      action: "stageSelectedFilesCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.StageSelectedFilesCommand"
      commandID: "Xcode.IDEKit.CmdDefinition.StageSelectedFilesCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Stage Selected Files"
  - id: "actions.git.push"
    name: "Push changes"
    description: "Push Changes"
    category: "Version Control"
    vscode:
      command: "git.pushTo"
      when: "git.state == 'initialized' && git.remotes.length > 0"
    intellij:
      action: "Git.Commit.And.Push.Executor"
    zed:
      action: "git::Push"
      context: "Editor"
    xcode:
      action: "pushCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.PushCommand"
      commandID: "Xcode.IDEKit.CmdDefinition.PushCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Push…"
  - id: "actions.git.sync"
    name: "Pull changes"
    description: "Pull changes"
    category: "Version Control"
    vscode:
      command: "git.sync"
      when: "git.state == 'initialized' && git.remotes.length > 0"
    intellij:
      action: "Vcs.UpdateProject"
    zed:
      action: "git::Pull"
      context: "Editor"
    xcode:
      action: "updateCommand:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.UpdateCommand"
      commandID: "Xcode.IDEKit.CmdDefinition.UpdateCommand"
      group: "Integrate Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Pull…"
  - id: "actions.git.toggleBlame"
    name: "Toggle blame"
    description: "Toggle Blame in left of editor"
    category: "Version Control"
    children:
      - "actions.git.blameHover"
      - "actions.git.toggleBlameInline"
      - "actions.git.toggleBlameStatusBar"
    fallbacks:
      - "actions.git.blameHover"
      - "actions.git.toggleBlameInline"
      - "actions.git.toggleBlameStatusBar"
    vscode:
      command: "git.blame.toggleEditorDecoration"
      note: "toggle blame inline"
      disableImport: true
    intellij:
      notSupported: true
      note: "intellij can only toggle blame in actions"
    zed:
      action: "git::blame"
      context: "Editor"
    xcode:
      - action: "toggleAuthorsShown:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowAuthors"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowAuthors"
        group: "Editor Menu for Playground"
        groupID: "Xcode.IDEPlaygroundEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Authors"
        disableImport: true
      - action: "toggleAuthorsShown:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowAuthors"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowAuthors"
        group: "Editor Menu for Source Code"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Authors"
  - id: "actions.git.toggleBlameInline"
    name: "Toggle blame inline"
    description: "Toggle blame inline, next to editor content"
    category: "Version Control"
    featured: true
    vscode:
      command: "git.blame.toggleEditorDecoration"
    zed:
      action: "editor::ToggleGitBlameInline"
    xcode:
      - action: "blameSelectedLine:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowBlameForLine"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowBlameForLine"
        group: "Editor Menu for Asset Catalog Comparison"
        groupID: "Xcode.DeltaComparisonEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Show Last Change for Line"
        disableImport: true
      - action: "blameSelectedLine:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowBlameForLine"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowBlameForLine"
        group: "Editor Menu for Playground"
        groupID: "Xcode.IDEPlaygroundEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Show Last Change for Line"
        disableImport: true
      - action: "blameSelectedLine:"
        alternate: "NO"
        commandGroupID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowBlameForLine"
        commandID: "Xcode.IDEPegasusSourceEditor.CmdDefinition.ShowBlameForLine"
        group: "Editor Menu for Source Code"
        groupID: "Xcode.IDEPegasusSourceEditor.MenuDefinition.Editor"
        groupedAlternate: "NO"
        navigation: "NO"
        title: "Show Last Change for Line"
  - id: "actions.git.toggleBlameStatusBar"
    name: "Toggle blame status bar"
    description: "Toggle blame in status bar"
    category: "Version Control"
    featured: true
    vscode:
      command: "git.blame.toggleStatusBarItem"
    zed:
      notSupported: true
      note: "not supported yet, see [`Optional Git Blame in status bar instead of inline` discussion](https://github.com/zed-industries/zed/discussions/26127)"
    xcode:
      notSupported: true
  - id: "actions.git.blameHover"
    name: "Blame hover"
    description: "Show blame information on hover"
    category: "Version Control"
    featured: true
    vscode:
      notSupported: true
      note: "vscode support blame inline, see `Toggle blame inline`"
    zed:
      action: "editor::BlameHover"
      context: "Editor"
    xcode:
      notSupported: true
  - id: "action.git.jumpSource"
    name: "Open source file from version control panel"
    description: "Jump to Source"
    category: "Version Control"
    vscode:
      command: "git.openFile"
      when: "config.git.enabled && isInDiffEditor"
    intellij:
      action: "EditSource"
