mappings:
  - id: "actions.view.showCommandPalette"
    name: "Show command palette"
    description: "Show Command Palette"
    category: "View Management"
    vscode:
      command: "workbench.action.showCommands"
      when: ""
    zed:
      action: "command_palette::Toggle"
      # Empty context means global
      context: ""
    intellij:
      action: "GotoAction"
    helix:
      command: "command_palette"
      mode: "insert"
    xcode:
      action: "showQuickActions:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.ShowQuickActions"
      commandID: "Xcode.IDEKit.CmdDefinition.ShowQuickActions"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Show Quick Actionsâ€¦"
