mappings:
  - id: "actions.view.openGlobalSettings"
    name: "Open global settings"
    description: "Open Global Settings"
    category: "View Management"
    vscode:
      command: "workbench.action.openGlobalSettings"
    intellij:
      action: "ShowSettingsAndFindPlugin"
    zed:
      action: "zed::OpenSettings"
    helix:
      command: ":config-open"
      mode: "insert"
    xcode:
      action: "showPreferencesPanel:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.Preferences"
      commandID: "Xcode.IDEKit.CmdDefinition.Preferences"
      group: "Xcode Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      title: "Settingsâ€¦"
  - id: "actions.view.selectTheme"
    name: "Select theme"
    description: "Select Theme"
    category: "View Management"
    vscode:
      command: "workbench.action.selectTheme"
    intellij:
      action: "QuickChangeScheme"
    zed:
      action: "theme_selector::Toggle"
      context: "Workspace"
    helix:
      command: ":theme"
      mode: "insert"
    xcode:
      notSupported: true
      note: "Xcode does not have a theme"
  - id: "actions.view.openKeyboardShortcuts"
    name: "Open keyboard shortcuts"
    description: "Open Keyboard Shortcuts Settings"
    category: "View Management"
    vscode:
      command: "workbench.action.openGlobalKeybindings"
    intellij:
      notSupported: true
      note: "intellij do not have open keyboard shortcuts, you can open `Keymap` in command palette searching for `Keymap` and then open it."
    zed:
      action: "zed::OpenKeymap"
      context: "Workspace"
    xcode:
      notSupported: true
      note: "use `Open global settings` instead"
