mappings:
  - id: "actions.view.focusNextSplit"
    name: "Focus next split"
    description: "Focus next editor split"
    category: "View Management.Split"
    vscode:
      command: "workbench.action.focusNextGroup"
      when: "editorFocus"
    intellij:
      action: "NextSplitter"
    zed:
      action: "workspace::ActivateNextPane"
      context: "Editor"
    helix:
      command: "rotate_view"
      mode: "insert"
  - id: "actions.view.focusPreviousSplit"
    name: "Focus previous split"
    description: "Focus previous editor split"
    category: "View Management.Split"
    vscode:
      command: "workbench.action.focusPreviousGroup"
      when: "editorFocus"
    intellij:
      action: "PrevSplitter"
    zed:
      action: "workspace::ActivatePreviousPane"
      context: "Editor"
    helix:
      command: "rotate_view_reverse"
      mode: "insert"
  - id: "actions.view.splitRight"
    name: "Split right"
    description: "Split editor to right"
    category: "View Management.Split"
    vscode:
      - command: "workbench.action.splitEditorRight"
        when: "editorFocus"
      - command: "workbench.action.terminal.split"
        when: "terminalFocus && terminalProcessSupported || terminalFocus && terminalWebExtensionContributedProfile"
    zed:
     # split editor
     - action: "pane::SplitRight"
       context: "Editor"
     # split terminal
     - action: "pane::SplitRight"
       context: "Terminal"
    intellij:
      action: "SplitVertically"
  - id: "actions.view.splitLeft"
    name: "Split left"
    description: "Split editor to left"
    category: "View Management.Split"
    featured: true
    featuredReason: "Not all editors support split left, use `Split right` instead."
    vscode:
      command: "workbench.action.splitEditorLeft"
      when: "editorFocus"
    zed:
      - action: "pane::SplitLeft"
        context: "Editor"
      - action: "pane::SplitLeft"
        context: "Terminal"
    intellij:
      notSupported: true
      note: "intellij do not have split left, use `Split right` instead."
  - id: "actions.view.splitUp"
    name: "Split up"
    description: "Split editor to up"
    category: "View Management.Split"
    featured: true
    featuredReason: "Not all editors support split up, use `Split down` instead."
    vscode:
      command: "workbench.action.splitEditorUp"
      when: "editorFocus"
    zed:
      - action: "pane::SplitUp"
        context: "Editor"
      - action: "pane::SplitUp"
        context: "Terminal"
    intellij:
     notSupported: true
     note: "intellij do not have split up, use `Split down` instead."
  - id: "actions.view.splitDown"
    name: "Split down"
    description: "Split editor to down"
    category: "View Management.Split"
    vscode:
      command: "workbench.action.splitEditorDown"
      when: "editorFocus"
    zed:
      - action: "pane::SplitDown"
        context: "Editor"
      - action: "pane::SplitDown"
        context: "Terminal"
    intellij:
     action: "SplitHorizontally"
