mappings:
  - id: "actions.view.toggleExplorer"
    name: "Toggle file explorer"
    description: "Toggle file explorer view"
    category: "View Management.Pannels"
    vscode:
      - command: "workbench.view.explorer"
        when: "viewContainer.workbench.view.explorer.enabled"
      - command: "workbench.action.toggleSidebarVisibility"
        when: "explorerViewletFocus"
        disableImport: true
    zed:
      action: "project_panel::ToggleFocus"
      context: "Workspace"
    intellij:
      action: "ActivateProjectToolWindow"
    helix:
      command: "file_explorer"
      mode: "insert"
    xcode:
      action: "toggleStructureNavigator:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.NavigatorsStructure"
      commandID: "Xcode.IDEKit.CmdDefinition.NavigatorsStructure"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Navigators"
      title: "Project"
  - id: "actions.view.toggleSearch"
    name: "Toggle search"
    description: "Toggle Search view"
    category: "View Management.Pannels"
    vscode:
      - command: "workbench.view.search"
        when: "workbench.view.search.active && neverMatch =~ /doesNotMatch/"
      - command: "workbench.action.toggleSidebarVisibility"
        when: "searchViewletVisible"
        disableImport: true
    zed:
      action: "project_search::ToggleFocus"
      context: "Workspace"
    intellij:
      action: "SearchEverywhere"
    helix:
      command: "global_search"
      mode: "insert"
    xcode:
      action: "toggleFindNavigator:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.NavigatorsFind"
      commandID: "Xcode.IDEKit.CmdDefinition.NavigatorsFind"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Navigators"
      title: "Find"
  - id: "actions.view.toggleSourceControl"
    name: "Toggle source control"
    description: "Toggle Source Control view"
    category: "View Management.Pannels"
    vscode:
      - command: "workbench.view.scm"
        when: "workbench.scm.active"
      - command: "workbench.action.toggleSidebarVisibility"
        when: "activeViewlet == 'workbench.view.scm'"
        disableImport: true
    zed:
      action: "git_panel::ToggleFocus"
      context: "Workspace"
    intellij:
      action: "ActivateVersionControlToolWindow"
    helix:
      command: "changed_file_picker"
      mode: "insert"
    xcode:
      action: "toggleWorkingCopiesNavigator:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.NavigatorsWorkingCopies"
      commandID: "Xcode.IDEKit.CmdDefinition.NavigatorsWorkingCopies"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Navigators"
      title: "Source Control"
  - id: "actions.view.showExtensions"
    name: "Show extensions"
    description: "Show Extensions view"
    category: "View Management.Pannels"
    vscode:
      command: "workbench.view.extensions"
      when: "viewContainer.workbench.view.extensions.enabled"
    zed:
      action: "zed::Extensions"
      context: "Workspace"
    intellij:
      action: "WelcomeScreen.Plugins"
    helix:
      notSupported: true
  - id: "actions.view.showTesting"
    name: "Show testing"
    description: "Show Testing view"
    category: "View Management.Pannels"
    vscode:
      command: "workbench.view.testing"
      when: ""
    zed:
      notSupported: true
      note: "zed do not have testing view"
    intellij:
      action: "ActivateUnitTestsToolWindow"
    helix:
      notSupported: true
    xcode:
      action: "toggleTestNavigator:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.NavigatorsTest"
      commandID: "Xcode.IDEKit.CmdDefinition.NavigatorsTest"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Navigators"
      title: "Tests"
  - id: "actions.view.toggleProblems"
    name: "Toggle problems"
    description: "Toggle Problems view"
    category: "View Management.Pannels"
    vscode:
      command: "workbench.actions.view.problems"
      when: ""
    zed:
      # TODO(xinnjie): can not close problems view yet
      action: "diagnostics::Deploy"
      context: "Workspace"
    intellij:
      action: "ActivateProblemsViewToolWindow"
    helix:
      command: "workspace_diagnostics_picker"
      mode: "insert"
    xcode:
      action: "toggleIssuesNavigator:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.NavigatorsIssues"
      commandID: "Xcode.IDEKit.CmdDefinition.NavigatorsIssues"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Navigators"
      title: "Issues"
  - id: "actions.view.toggleOutput"
    name: "Toggle output"
    description: "Toggle Output view"
    category: "View Management.Pannels"
    vscode:
      command: "workbench.action.output.toggleOutput"
      when: "workbench.panel.output.active"
    zed:
      notSupported: true
      note: "zed do not have output view"
    intellij:
      action: "ActivateRunToolWindow"
    helix:
      notSupported: true
  - id: "actions.view.toggleTerminal"
    name: "Toggle terminal"
    description: "Toggle Terminal view"
    category: "View Management.Pannels"
    vscode:
      command: "workbench.action.terminal.toggleTerminal"
      when: "terminal.active"
    zed:
      action: "terminal_panel::ToggleFocus"
      context: "Workspace"
    intellij:
      action: "ActivateTerminalToolWindow"
    helix:
      notSupported: true
  - id: "actions.view.toggleDebugPanel"
    name: "Toggle debug panel"
    description: "Toggle Debug Panel"
    category: "View Management.Pannels"
    vscode:
      - command: "workbench.view.debug"
        when: "viewContainer.workbench.view.debug.enabled"
      - command: "workbench.action.toggleSidebarVisibility"
        when: "activeViewlet == 'workbench.view.debug'"
        disableImport: true
    zed:
      action: "debug_panel::ToggleFocus"
      context: "Workspace"
    intellij:
      action: "ActivateDebugToolWindow"
    helix:
      notSupported: true
    xcode:
      action: "toggleDebuggerVisibility:"
      alternate: "NO"
      commandGroupID: "Xcode.IDEKit.CmdDefinition.DebuggerToggleVisibility"
      commandID: "Xcode.IDEKit.CmdDefinition.DebuggerToggleVisibility"
      group: "View Menu"
      groupID: "Xcode.IDEKit.MenuDefinition.Main"
      groupedAlternate: "NO"
      navigation: "NO"
      parentTitle: "Debug Area"
      title: "Show Debug Area"
